### PR TITLE
Navigate

### PR DESCRIPTION
**Pull request by netsquire**
Please review request 'Navigation Tree'!

### CODE REVIEW

**Comment by mattmahoneyrh** [comment]
Tried to run a couple of validation tests, but both fail test_all_navegitions() and _test_all_navegitions_2()
See: see http://pastebin.test.redhat.com/380363

Is navigation.py line 117 (pivot = elem) stepping on the web-driver?

**Comment by netsquire** [comment]
without MIQ_HOSTNAME set to correct IP, test run produces: "WebDriverException: Message: Target URL http://:80/ is not well-formed."

**Comment by netsquire** [comment]
MIQ_HOSTNAME set to empty.

**Comment by mattmahoneyrh** [comment]
Test passed - will merge.

**Pull request closed without merging**
