### PR TITLE
vnc to flv and deploy

### PR DESCRIPTION
**Pull request by vprusa**
Failing test - ```tests/framework/test_failing.py```
Utils - test recording and deploying to PRs with live terminal, additional properties
Scripts - automation scripts moved to ```scripts/automation/*.sh```

### CODE REVIEW

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [111](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/111/)
<br> No records available

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [112](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/112/)
<br> No records available

**Comment by vprusa** [comment]
ok to test
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [113](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/113/)
<br> Gif records:<br>

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [114](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/114/)
<br> Gif records:<br> - [record_test_failing.flv](http://10.16.23.184/records/114/record_test_failing.flv) <br>

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [115](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/115/)
<br> Gif records:<br> - [record_test_failing.flv](http://10.16.23.184/records/115/record_test_failing.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [116](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/116/)
<br> Gif records:<br> - [record_test_failing.flv](http://10.16.23.184/records/116/record_test_failing.flv) <br>

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [117](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/117/)
<br> Gif records:<br> - [record_test_datasource.flv](http://10.16.23.184/records/117/record_test_datasource.flv) <br> - [record_test_deployments.flv](http://10.16.23.184/records/117/record_test_deployments.flv) <br> - [record_test_providers.flv](http://10.16.23.184/records/117/record_test_providers.flv) <br> - [record_test_servers.flv](http://10.16.23.184/records/117/record_test_servers.flv) <br> - [record_test_topology.flv](http://10.16.23.184/records/117/record_test_topology.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [119](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/119/)
<br> Gif records:<br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [120](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/120/)
<br> Gif records:<br> - [record_test_datasource.flv](http://10.16.23.184/records/120/record_test_datasource.flv) <br> - [record_test_deployments.flv](http://10.16.23.184/records/120/record_test_deployments.flv) <br> - [record_test_providers.flv](http://10.16.23.184/records/120/record_test_providers.flv) <br> - [record_test_servers.flv](http://10.16.23.184/records/120/record_test_servers.flv) <br> - [record_test_topology.flv](http://10.16.23.184/records/120/record_test_topology.flv) <br>

**Comment by vprusa** [comment]
ok to test
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [123](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/123/)
<br> Gif records:<br> - [record_test_failing.flv](http://10.16.23.184/records/123/record_test_failing.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [124](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/124/)
<br> Gif records:<br> - [record_test_failing.flv](http://10.16.23.184/records/124/record_test_failing.flv) <br>

**Comment by vprusa** [comment]
ok to test
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [125](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/125/)
<br> Gif records:<br>

**Comment by vprusa** [comment]
ok to test
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [126](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/126/)
<br> Gif records:<br> - [record_test_failing.flv](http://10.16.23.184/records/126/record_test_failing.flv) <br>

**Comment by vprusa** [comment]
ok to test
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [127](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/127/)
<br> Gif records:<br> - [record_test_failing.flv](http://10.16.23.184/records/127/record_test_failing.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [128](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/128/)
<br> Gif records:<br> - [record_test_failing.flv](http://10.16.23.184/records/128/record_test_failing.flv) <br>

**Comment by vprusa** [comment]
ok to test
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [129](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/129/)
<br> Gif records:<br>

**Comment by vprusa** [comment]
ok to test
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [130](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/130/)
<br> Gif records:<br> - [record_test_datasource.flv](http://10.16.23.184/records/130/record_test_datasource.flv) <br> - [record_test_deployments.flv](http://10.16.23.184/records/130/record_test_deployments.flv) <br> - [record_test_providers.flv](http://10.16.23.184/records/130/record_test_providers.flv) <br> - [record_test_servers.flv](http://10.16.23.184/records/130/record_test_servers.flv) <br> - [record_test_topology.flv](http://10.16.23.184/records/130/record_test_topology.flv) <br>

**Comment by vprusa** [comment]
Please review @mattmahoneyrh

**Pull request merged**
