### PR TITLE
added test case for middleware domain

### PR DESCRIPTION
**Pull request by prachiyadav**

### CODE REVIEW

**Comment by mattmahoneyrh** [comment]
This can be removed - because it really does not test anything.

 for i in r:
      assert os.path.exists(i)

A similar example of why that is, would be something like:
 fileList = `ls`
for eachFile in fileList
  Assert (if file does not exist)   <-- The file will always be there, because it came from fileList

Can instead check in the fileList as to whether these two expected files exist:
 Middleware*.txt
 Middleware*.csv

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [193](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/193/)
<br> Gif records:<br> - [record_test_datasource.flv](http://10.16.23.184/records/193/record_test_datasource.flv) <br> - [record_test_deployments.flv](http://10.16.23.184/records/193/record_test_deployments.flv) <br> - [record_test_domains.flv](http://10.16.23.184/records/193/record_test_domains.flv) <br> - [record_test_download_report.flv](http://10.16.23.184/records/193/record_test_download_report.flv) <br> - [record_test_providers.flv](http://10.16.23.184/records/193/record_test_providers.flv) <br> - [record_test_servers.flv](http://10.16.23.184/records/193/record_test_servers.flv) <br> - [record_test_topology.flv](http://10.16.23.184/records/193/record_test_topology.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [209](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/209/)
<br> Gif records:<br> - [record_test_datasource.flv](http://10.16.23.184/records/209/record_test_datasource.flv) <br> - [record_test_deployments.flv](http://10.16.23.184/records/209/record_test_deployments.flv) <br> - [record_test_domains.flv](http://10.16.23.184/records/209/record_test_domains.flv) <br> - [record_test_download_report.flv](http://10.16.23.184/records/209/record_test_download_report.flv) <br> - [record_test_providers.flv](http://10.16.23.184/records/209/record_test_providers.flv) <br> - [record_test_servers.flv](http://10.16.23.184/records/209/record_test_servers.flv) <br> - [record_test_topology.flv](http://10.16.23.184/records/209/record_test_topology.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [211](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/211/)
<br> Gif records:<br> - [record_test_datasource.flv](http://10.16.23.184/records/211/record_test_datasource.flv) <br> - [record_test_deployments.flv](http://10.16.23.184/records/211/record_test_deployments.flv) <br> - [record_test_domains.flv](http://10.16.23.184/records/211/record_test_domains.flv) <br> - [record_test_download_report.flv](http://10.16.23.184/records/211/record_test_download_report.flv) <br> - [record_test_providers.flv](http://10.16.23.184/records/211/record_test_providers.flv) <br> - [record_test_servers.flv](http://10.16.23.184/records/211/record_test_servers.flv) <br> - [record_test_topology.flv](http://10.16.23.184/records/211/record_test_topology.flv) <br>

**Pull request merged**
