### PR TITLE
Docker with EAP7 - domain & standalone mode & both

### PR DESCRIPTION
**Pull request by vprusa**
[Read this](https://github.com/Hawkular-QE/cf-ui/blob/f4024edd808ed29e081c69985bb0c4a256db4c2f/scripts/automation/docker/startHawkularServices/README.md)

Updated according to https://docs.engineering.redhat.com/display/JP/CloudForms+Middleware+-+Quickstart+Guide - added providing EAP7 via docker - domain & standalone mode & both 

Please review but dont merge just yet

### CODE REVIEW

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [221](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/221/)
<br> Gif records:<br> - [record_test_datasource.flv](http://10.16.23.184/records/221/record_test_datasource.flv) <br> - [record_test_deployments.flv](http://10.16.23.184/records/221/record_test_deployments.flv) <br> - [record_test_domains.flv](http://10.16.23.184/records/221/record_test_domains.flv) <br> - [record_test_download_report.flv](http://10.16.23.184/records/221/record_test_download_report.flv) <br> - [record_test_providers.flv](http://10.16.23.184/records/221/record_test_providers.flv) <br> - [record_test_servers.flv](http://10.16.23.184/records/221/record_test_servers.flv) <br> - [record_test_topology.flv](http://10.16.23.184/records/221/record_test_topology.flv) <br>

**Comment by vprusa** [comment]
Docker wrapper HS+Cass with EAP7 - domain & standalone mode & both, refactored - common.sh, udpated to latest changes, added cfme wrapper, source relative, readme updated

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [225](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/225/)
<br> No records available

**Comment by vprusa** [comment]
ok to test
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [229](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/229/)
<br> Gif records:<br> - [record_test_datasource.flv](http://10.16.23.184/records/229/record_test_datasource.flv) <br> - [record_test_deployments.flv](http://10.16.23.184/records/229/record_test_deployments.flv) <br> - [record_test_domains.flv](http://10.16.23.184/records/229/record_test_domains.flv) <br> - [record_test_download_report.flv](http://10.16.23.184/records/229/record_test_download_report.flv) <br> - [record_test_providers.flv](http://10.16.23.184/records/229/record_test_providers.flv) <br> - [record_test_servers.flv](http://10.16.23.184/records/229/record_test_servers.flv) <br> - [record_test_topology.flv](http://10.16.23.184/records/229/record_test_topology.flv) <br>

**Comment by mattmahoneyrh** [comment]
Encountered this when attempting to run on Fedora:

Starting docker.io/HSqe/HS-services
docker: Error parsing reference: "docker.io/HSqe/HS-services" is not a valid repository/tag.
See 'docker run --help'.
Trying to get http://mm-dr2-fedora.bc.jonqe.lab.eng.bos.redhat.com:8080/hawkular/inventory/status
Got response

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [234](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/234/)
<br> Gif records:<br> - [record_test_datasource.flv](http://10.16.23.184/records/234/record_test_datasource.flv) <br> - [record_test_deployments.flv](http://10.16.23.184/records/234/record_test_deployments.flv) <br> - [record_test_domains.flv](http://10.16.23.184/records/234/record_test_domains.flv) <br> - [record_test_download_report.flv](http://10.16.23.184/records/234/record_test_download_report.flv) <br> - [record_test_providers.flv](http://10.16.23.184/records/234/record_test_providers.flv) <br> - [record_test_servers.flv](http://10.16.23.184/records/234/record_test_servers.flv) <br> - [record_test_timeline.flv](http://10.16.23.184/records/234/record_test_timeline.flv) <br> - [record_test_topology.flv](http://10.16.23.184/records/234/record_test_topology.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [236](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/236/)
<br> No records available

**Pull request merged**
