### PR TITLE
Tags add/delete, added lambda

### PR DESCRIPTION
**Pull request by netsquire**
Cleaned up old commit, for transparency.
Reduced number of changed files.

### CODE REVIEW

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [214](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/214/)
<br> Gif records:<br> - [record_test_datasource.flv](http://10.16.23.184/records/214/record_test_datasource.flv) <br> - [record_test_deployments.flv](http://10.16.23.184/records/214/record_test_deployments.flv) <br> - [record_test_domains.flv](http://10.16.23.184/records/214/record_test_domains.flv) <br> - [record_test_providers.flv](http://10.16.23.184/records/214/record_test_providers.flv) <br> - [record_test_servers.flv](http://10.16.23.184/records/214/record_test_servers.flv) <br> - [record_test_topology.flv](http://10.16.23.184/records/214/record_test_topology.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [215](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/215/)
<br> Gif records:<br> - [record_test_datasource.flv](http://10.16.23.184/records/215/record_test_datasource.flv) <br> - [record_test_deployments.flv](http://10.16.23.184/records/215/record_test_deployments.flv) <br> - [record_test_domains.flv](http://10.16.23.184/records/215/record_test_domains.flv) <br> - [record_test_providers.flv](http://10.16.23.184/records/215/record_test_providers.flv) <br> - [record_test_servers.flv](http://10.16.23.184/records/215/record_test_servers.flv) <br> - [record_test_topology.flv](http://10.16.23.184/records/215/record_test_topology.flv) <br>

**Comment by mattmahoneyrh** [comment]
Ran the following:

py.test tests/framework/test_tags.py

Result:
======= 3 failed, 4 passed in 133.40 seconds =========

**Comment by mattmahoneyrh** [comment]
Note: "This branch has conflicts that must be resolved"

The Conflicts will need to be resolved, once the tests run cleanly against FF and Chrome.

**Comment by mattmahoneyrh** [comment]
Note: 3 of 7 tests failed (running w/ Chrome)
         1 of 7 tests failed (running w/ FF)

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [240](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/240/)
<br> Gif records:<br> - [record_test_datasource.flv](http://10.16.23.184/records/240/record_test_datasource.flv) <br> - [record_test_deployments.flv](http://10.16.23.184/records/240/record_test_deployments.flv) <br> - [record_test_domains.flv](http://10.16.23.184/records/240/record_test_domains.flv) <br> - [record_test_providers.flv](http://10.16.23.184/records/240/record_test_providers.flv) <br> - [record_test_servers.flv](http://10.16.23.184/records/240/record_test_servers.flv) <br> - [record_test_topology.flv](http://10.16.23.184/records/240/record_test_topology.flv) <br>

**Pull request closed without merging**
