### PR TITLE
Fixes and utils #1

### PR DESCRIPTION
**Pull request by vprusa**
common/ui_utils.py
Select just visible text and add functionality, that enables waiting for text to disappear.

parsing/table.py
For tables i can wait for 60s until MW providers data loads, assert is eventually fired later in table parsing.

tests/test_servers.py
After CRUD tests of test_providers.py there was no MW provider.

### CODE REVIEW

**Comment by vprusa** [comment]
Test this please

**Comment by vprusa** [comment]
test this please

**Comment by vprusa** [comment]
test this please

**Comment by vprusa** [comment]
test this please

**Comment by mattmahoneyrh** [comment]
When the session object is created, there is a check whether the provider exists or not, as well as an argument to session "add_provider" which defaults to True. There there should be no need for the test case to first add the provider.

**Comment by vprusa** [comment]
Ah, i see, my bad, then on Jenkins MIQ needs just wait some time for provider to load data from Hawkular about its/MW servers.

**Comment by mattmahoneyrh** [comment]
Yes, there is an enhancement on the way to address the need to wait for the newly added provider to do it's firs Refresh, which will bring in the Servers/Deployments/etc.

**Comment by vprusa** [comment]
test this please

**Comment by vprusa** [comment]
test this please

**Comment by vprusa** [comment]
test this please

**Comment by vprusa** [comment]
test this please

**Pull request merged**
