### PR TITLE
Skip 'error' tags text value and make sure it has 'type'.

### PR DESCRIPTION
**Pull request by hhovsepy**
According to the last 'xml' template of Polarion XUnit exporter.

### CODE REVIEW

**Comment by hawkularqe** [comment]
Can one of the admins verify this patch?

**Comment by mattmahoneyrh** [comment]
What is the reason for this proposed change? Is the Jenkins Polarion Exporter not working for the said tags when exporting CFME-Tests results?

**Comment by hhovsepy** [comment]
CFME-Tests results does not have these tags so far, so we never faced this problem.
This is preventive modification, making sure that export will not fail if these tags exist, especially when they are not acceptable in Polarion, and of course unnecessary.

**Comment by hhovsepy** [comment]
As I understood this script is common not only for CFME-Tests, so my suggestion is to have all possible restrictions in Polarion to be skipped by this script, even if we did not faced it so far.

**Pull request merged**
