### PR TITLE
add Alert test case added

### PR DESCRIPTION
**Pull request by prachiyadav**
Add alert Test case is added.... but need to refactor once others are added. 
Do not Merge.

### CODE REVIEW

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [254](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/254/)
<br> Gif records:<br> - [record_test_alert.flv](http://10.16.23.184/records/254/record_test_alert.flv) <br> - [record_test_datasource.flv](http://10.16.23.184/records/254/record_test_datasource.flv) <br> - [record_test_deployments.flv](http://10.16.23.184/records/254/record_test_deployments.flv) <br> - [record_test_domains.flv](http://10.16.23.184/records/254/record_test_domains.flv) <br> - [record_test_download_report.flv](http://10.16.23.184/records/254/record_test_download_report.flv) <br> - [record_test_messagings.flv](http://10.16.23.184/records/254/record_test_messagings.flv) <br> - [record_test_providers.flv](http://10.16.23.184/records/254/record_test_providers.flv) <br> - [record_test_servers.flv](http://10.16.23.184/records/254/record_test_servers.flv) <br> - [record_test_timeline.flv](http://10.16.23.184/records/254/record_test_timeline.flv) <br> - [record_test_topology.flv](http://10.16.23.184/records/254/record_test_topology.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [264](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/264/)
<br> No records available

**Comment by prachiyadav** [comment]
Do not merge. Editing the same.

**Comment by mattmahoneyrh** [comment]
XPath refactoring needed to support latest CFME.

**Comment by mattmahoneyrh** [comment]
Please resolve this issue prior to merging:

py.test tests/test_alert.py 
========================================================================== test session starts ===========================================================================
platform linux2 -- Python 2.7.5, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /home/mmahoney/Repository/T/cf-ui, inifile: 
plugins: wait-for-1.0.6
collected 0 items / 1 errors 

================================================================================= ERRORS =================================================================================
__________________________________________________________________ ERROR collecting tests/test_alert.py __________________________________________________________________
.cf-ui/lib/python2.7/site-packages/_pytest/python.py:410: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.cf-ui/lib/python2.7/site-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
.cf-ui/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:207: in load_module
    py.builtin.exec_(co, mod.__dict__)
tests/test_alert.py:3: in <module>
    from common.eap_alerts import eap_alerts
E     File "/home/mmahoney/Repository/T/cf-ui/common/eap_alerts.py", line 69
E       assert ui_utils(self.web_session).waitForTextOnPage("All Alerts", 15).click()
E      ^
E   IndentationError: unexpected indent
---------------------------------------------------------------------------- Captured stderr ---------------------------------------------------------------------------

**Comment by prachiyadav** [comment]
Working on It

**Comment by mattmahoneyrh** [comment]
There are a couple of issues that I experienced when attempting to run these new tests:

 1) There is an indent issue at line 68/69.
 2) It appears that your branch is running against an older version of CFME, which is causing a failure to locate element at common/eap_alerts.py:33
     I believe (but have not validated) that you are running against an older CFME because when running in the eap-alerts branch against latest CFME the add_provider fails in a place that is due to running with older provider code.
    Also, when I bring your two new alert files into my latest cf-me, te test fails due to element location issue, which most likely, again, is due to being writing against an older CFME.

Please ensure you pull the latest CFME build, and then run your tests against that - refactoring code that may be broken.

**Comment by mattmahoneyrh** [comment]
Can this branch be deleted, as it appears that complete-Alert-test has replaced this one?

**Pull request closed without merging**
