### PR TITLE
Table parsing

### PR DESCRIPTION
**Pull request by netsquire**
Please review!
Joined branches 'table-parsing' and 'navigate'

### CODE REVIEW

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [175](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/miq-mw-ui-tests/175/)
<br> Gif records:<br>

**Comment by mattmahoneyrh** [comment]
properties.properties should not be modified, especially with actual URL's.

In general - please clarify the following:
 - What Trello task is this code representing?
 - What feature or problem is code resolving?
 - Is there another cf-ui component/method that is already implemented?

**Comment by mattmahoneyrh** [comment]
This PR appears to no longer be relevant. Please cancel if that is the case.

**Comment by netsquire** [comment]
to close!

**Pull request closed without merging**
